### ISSUE TITLE
Import fails for non-paired data

### ISSUE THREAD

**Issue by aknijn** [phac-nml/irida-galaxy-importer#2]
The importer works fine for paired data, however when I try to import non-paired data, the following error occurs in our Galaxy instance:
Traceback (most recent call last):
  File "/zzz/galaxy-dist/tools/irida_import/irida_import.py", line 816, in <module>
    token=args.token)
  File "/zzz/galaxy-dist/tools/irida_import/irida_import.py", line 735, in import_to_galaxy
    samples = self.get_samples(samples_dict)
  File "/zzz/galaxy-dist/tools/irida_import/irida_import.py", line 97, in get_samples
    sample.add_file(self.get_sample_file(single))
  File "/zzz/galaxy-dist/tools/irida_import/irida_import.py", line 166, in get_sample_file
    name = resource['fileName']
KeyError: 'fileName'

Do you have some idea why this happens?

**Comment by ericenns** [comment]
Yes, this is a confirmed issue. We have a fix for it, and will try to push a new release later today.

**Comment by ericenns** [comment]
Hi, this has been fixed in 544cfe6af93c177fac60fefc7ca35ad7ec1fb5f5 and merged into development and master.
